# Archive exploration

- Where was the data collected from??
Upper Colorado River Basin
Bounding Coordinates:
- West: −119.35547
- East: −103.71094
- North: 31.65338
- South: 41.77131

- During what time frame were the observations in the dataset collected?
January 1, 2005 to December 31, 2021

- What was the author’s perceived value of this dataset?
The authors value the dataset as a tool for identifying water conflict hotspots and understanding social vulnerability and institutional resilience in the Colorado River Basin. It supports ongoing USGS research and informs future water availability assessments.

### Dataset Overview: Coded Water Conflict and Crisis Events in the Colorado River Basin (2005–2021)

This dataset documents water-related conflict and crisis events in the Upper Colorado River Basin, bounded by coordinates West: −119.35547, East: −103.71094, North: 31.65338, and South: 41.77131. Observations were collected between January 1, 2005 and December 31, 2021. The authors regard the dataset as a valuable resource for identifying conflict hotspots and analyzing social vulnerability and institutional resilience, contributing to ongoing USGS research and future water availability assessments.

**Citation**: Holloman, D.V., Hines, M.K., Zoanni, D.K. (2023). *Coded Water Conflict and Crisis Events in the Colorado River Basin, Derived from LexisNexis search 2005–2021*. U.S. Geological Survey.  
**Date of Access**: October 9, 2025  
**Archive Link**: [ScienceBase Catalog Entry](https://www.sciencebase.gov/catalog/item/63acac09d34e92aad3ca1480)

# Data loading

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('data/Colorado River Basin Water Conflict Table.csv')

# Preliminary data exploration

In [5]:
display(df.columns)

Index(['Event', 'Search Source', 'Newspaper', 'Article Title', 'Duplicate',
       'Report Date', 'Report Year', 'Event Date', 'Event Day', 'Event Month',
       'Event Year', 'Conflict Present', 'Crisis Present', 'Basin', 'HUC6',
       'HUC2', 'Place', 'County', 'County FIPS', 'State', 'State FIPS',
       'Urban or Rural', 'Issue Type', 'Event Summary', 'Stakeholders',
       'Intensity Value', 'Comments', 'Related Observation Themes',
       'Article Text Search - water quality',
       'Article Text Search - invasive species',
       'Article Text Search - conservation', 'Article Text Search - drought',
       'Article Text Search - flood',
       'Article Text Search - ground water depletion',
       'Article Text Search - depletion',
       'Article Text Search - infrastructure',
       'Article Text Search - fish passage',
       'Article Text Search - instream water rights',
       'Article Text Search - water rights',
       'Article Text Search - intergovernmental',
       'Article Text Search - water transfers',
       'Article Text Search - navigation', 'Article Text Search - fish',
       'Article Text Search - invasive', 'Article Text Search - diversion',
       'Article Text Search - water diversion',
       'Article Text Search - instream', 'Article Text Search - aquatic'],
      dtype='object')

In [17]:
df.head()

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,...,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,1,USGS1-50.docx,The Durango Herald (Colorado),Tribes assert water rights on Colorado River B...,False,7-Apr-22,2022.0,NaN,NaN,4.0,...,17,0,0,0,0,0,0,0,0,0
1,2,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Native American tribes assert water rights on ...,False,7-Apr-22,2022.0,NaN,NaN,4.0,...,17,0,0,0,0,0,0,0,0,0
2,3,USGS1-50.docx,The Salt Lake Tribune,'Very positive change.' New Utah law will be a...,False,17-Mar-22,2022.0,NaN,NaN,3.0,...,12,0,0,0,1,0,0,0,12,1
3,4,USGS1-50.docx,Casa Grande Dispatch (AZ),Legislation would let an Arizona tribe lease C...,False,11-Dec-21,2021.0,NaN,NaN,12.0,...,6,0,0,0,0,0,0,0,0,0
4,5,USGS1-50.docx,The Aspen Times (Colorado),Historically excluded from Colorado River poli...,False,19-Dec-21,2021.0,NaN,NaN,11.0,...,18,0,0,0,0,0,0,0,0,0

In [10]:
df.describe()

,Event,Report Year,Event Day,Event Month,Event Year,County FIPS,Intensity Value,Article Text Search - water quality,Article Text Search - invasive species,Article Text Search - conservation,...,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
count,268.000000,265.000000,18.000000,212.000000,257.000000,8.000000,255.000000,268.000000,268.000000,268.000000,...,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000
mean,134.500000,2017.449057,18.444444,6.259434,2016.591440,11170.500000,0.219608,0.671642,0.014925,2.007463,...,3.134328,0.003731,0.022388,0.007463,0.410448,0.033582,0.182836,0.011194,0.089552,0.093284
std,77.509139,4.314160,6.887518,3.679539,10.346365,15437.657326,1.995765,1.472729,0.121481,2.633681,...,3.456072,0.061085,0.148219,0.086225,1.109798,0.200166,0.734493,0.105405,0.860822,0.632064
min,1.000000,2005.000000,4.000000,1.000000,1900.000000,4027.000000,-4.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,67.750000,2015.000000,13.250000,3.000000,2015.000000,4027.000000,-1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,134.500000,2019.000000,19.000000,5.000000,2019.000000,6047.000000,0.000000,0.000000,0.000000,1.000000,...,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,201.250000,2021.000000,20.000000,9.000000,2021.000000,8067.000000,1.500000,1.000000,0.000000,3.000000,...,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,268.000000,2022.000000,31.000000,12.000000,2023.000000,49055.000000,5.000000,10.000000,1.000000,15.000000,...,18.000000,1.000000,1.000000,1.000000,8.000000,2.000000,7.000000,1.000000,12.000000,9.000000

In [8]:
df.shape

(268, 48)

In [14]:
df.isnull().sum()

Event                                             0
Search Source                                     0
Newspaper                                         0
Article Title                                     0
Duplicate                                         1
Report Date                                       1
Report Year                                       3
Event Date                                       20
Event Day                                       250
Event Month                                      56
Event Year                                       11
Conflict Present                                 16
Crisis Present                                   14
Basin                                            18
HUC6                                            158
HUC2                                             18
Place                                            14
County                                          260
County FIPS                                     260
State                                            90
State FIPS                                       90
Urban or Rural                                   14
Issue Type                                       13
Event Summary                                    12
Stakeholders                                     13
Intensity Value                                  13
Comments                                         78
Related Observation Themes                      182
Article Text Search - water quality               0
Article Text Search - invasive species            0
Article Text Search - conservation                0
Article Text Search - drought                     0
Article Text Search - flood                       0
Article Text Search - ground water depletion      0
Article Text Search - depletion                   0
Article Text Search - infrastructure              0
Article Text Search - fish passage                0
Article Text Search - instream water rights       0
Article Text Search - water rights                0
Article Text Search - intergovernmental           0
Article Text Search - water transfers             0
Article Text Search - navigation                  0
Article Text Search - fish                        0
Article Text Search - invasive                    0
Article Text Search - diversion                   0
Article Text Search - water diversion             0
Article Text Search - instream                    0
Article Text Search - aquatic                     0
dtype: int64

In [18]:
df.dtypes

Event                                             int64
Search Source                                    object
Newspaper                                        object
Article Title                                    object
Duplicate                                        object
Report Date                                      object
Report Year                                     float64
Event Date                                       object
Event Day                                       float64
Event Month                                     float64
Event Year                                      float64
Conflict Present                                 object
Crisis Present                                   object
Basin                                            object
HUC6                                             object
HUC2                                             object
Place                                            object
County                                           object
County FIPS                                     float64
State                                            object
State FIPS                                       object
Urban or Rural                                   object
Issue Type                                       object
Event Summary                                    object
Stakeholders                                     object
Intensity Value                                 float64
Comments                                         object
Related Observation Themes                       object
Article Text Search - water quality               int64
Article Text Search - invasive species            int64
Article Text Search - conservation                int64
Article Text Search - drought                     int64
Article Text Search - flood                       int64
Article Text Search - ground water depletion      int64
Article Text Search - depletion                   int64
Article Text Search - infrastructure              int64
Article Text Search - fish passage                int64
Article Text Search - instream water rights       int64
Article Text Search - water rights                int64
Article Text Search - intergovernmental           int64
Article Text Search - water transfers             int64
Article Text Search - navigation                  int64
Article Text Search - fish                        int64
Article Text Search - invasive                    int64
Article Text Search - diversion                   int64
Article Text Search - water diversion             int64
Article Text Search - instream                    int64
Article Text Search - aquatic                     int64
dtype: object

# String accesor for pandas.Series

In [ ]:
# Example series
s = pd.Series(['California; Nevada', 'Arizona', np.nan, 'Nevada; Utah'])
s

What are the unique values in the States column once filtering the dataset for states that have a water conflict?

In [11]:
pd.set_option("display.max.columns", None)
df.head()

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,Event Year,Conflict Present,Crisis Present,Basin,HUC6,HUC2,Place,County,County FIPS,State,State FIPS,Urban or Rural,Issue Type,Event Summary,Stakeholders,Intensity Value,Comments,Related Observation Themes,Article Text Search - water quality,Article Text Search - invasive species,Article Text Search - conservation,Article Text Search - drought,Article Text Search - flood,Article Text Search - ground water depletion,Article Text Search - depletion,Article Text Search - infrastructure,Article Text Search - fish passage,Article Text Search - instream water rights,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,1,USGS1-50.docx,The Durango Herald (Colorado),Tribes assert water rights on Colorado River B...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Tribal Nations, State Government, Federal Gove...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,3,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
1,2,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Native American tribes assert water rights on ...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Southern Ute Indian Tribe, Ute Mountain Tribe,...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,2,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
2,3,USGS1-50.docx,The Salt Lake Tribune,'Very positive change.' New Utah law will be a...,False,17-Mar-22,2022.0,NaN,NaN,3.0,2022.0,N,Y,Great Salt Lake,160203,16,Great Salt Lake,NaN,NaN,UT,49,Both,Instream water rights,A bill is proposed in Utah that would expand t...,"State Government, Any Water Rights Holder, Agr...",3.0,The event is the proposal of the bill at the s...,Dishonoring the absent,0,0,1,2,0,0,0,0,0,0,12,0,0,0,1,0,0,0,12,1
3,4,USGS1-50.docx,Casa Grande Dispatch (AZ),Legislation would let an Arizona tribe lease C...,False,11-Dec-21,2021.0,NaN,NaN,12.0,2021.0,N,Y,Lower Colorado,150301,15,Colorado River Indian Reservation,NaN,NaN,NaN,NaN,Rural,Water rights more generally,The Colorado River Indian Tribes Water Resilie...,"Colorado River Indian Tribes, State Government...",3.0,"Event is proposal of the bill, preliminary agr...",NaN,0,0,2,6,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0
4,5,USGS1-50.docx,The Aspen Times (Colorado),Historically excluded from Colorado River poli...,False,19-Dec-21,2021.0,NaN,NaN,11.0,2021.0,Y,Y,Upper San Juan,140801,14,Southern Ute Indian Reservation,NaN,NaN,NaN,NaN,Rural,Intergovernmental issues,State and federal officials say that Tribal Na...,"Sothern Ute Indian Tribe, Ute Mountain Tribe, ...",-1.0,Interaction between tribal nations and state/f...,Lack of tribal representation,0,0,2,6,0,0,0,7,0,0,18,0,0,0,0,0,0,0,0,0

In [13]:
conflict_present  =  df[df['Conflict Present'] == 'Y']

In [14]:
df['State'].unique()

array(['CO', 'UT', nan, 'AZ', 'OH; UT', 'AZ; CO; NM; UT', 'CA', 'AZ; UT',
       'AZ; NV', 'CO; UT; WY; NM', 'AZ; CA', 'UT; AZ', 'CO; WY', 'NV; AZ',
       'CO; AZ', 'AZ; CA; CO; NV; NM; UT; WY', 'AZ; CA; NV', 'NV', 'NM',
       'UT; CO; WY', 'CA; NV; AZ', 'AZ; NM', 'WY; UT; CO', 'TX'],
      dtype=object)

Individually, write step-by-step instructions on how you would wrangle the data frame df to obtain a list (without repetition) of the state codes in which a water conflict has been reported. It’s ok if you don’t know how to code each step - it’s more important to have an idea of what you would like to do.

1. Find unique spelling cases
2. Call the State column
3. Apply the string methods to remove spacing 
4. Use separator (;) to split

In [35]:
series_wrangled = df['State'].str.split(';', expand=True).stack()

array(['CO', 'UT', 'AZ', 'OH', 'NM', 'CA', 'NV', 'WY', 'TX'], dtype=object)

In [30]:
df_wrangled

0    0     CO
1    0     CO
2    0     UT
5    0     AZ
11   0     OH
         ...
264  0     CO
265  0     AZ
     1     CA
266  0     AZ
267  0     AZ
Length: 230, dtype: object

In [63]:
df_clean = df['State'].str.split('; ', expand=True).stack().unique()

In [64]:
df_clean

array(['CO', 'UT', 'AZ', 'OH', 'NM', 'CA', 'NV', 'WY', 'TX'], dtype=object)

In [57]:
df_conflict = df[df['Conflict Present'] == 'Y']

In [58]:
display(df_conflict)

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,Event Year,Conflict Present,Crisis Present,Basin,HUC6,HUC2,Place,County,County FIPS,State,State FIPS,Urban or Rural,Issue Type,Event Summary,Stakeholders,Intensity Value,Comments,Related Observation Themes,Article Text Search - water quality,Article Text Search - invasive species,Article Text Search - conservation,Article Text Search - drought,Article Text Search - flood,Article Text Search - ground water depletion,Article Text Search - depletion,Article Text Search - infrastructure,Article Text Search - fish passage,Article Text Search - instream water rights,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,1,USGS1-50.docx,The Durango Herald (Colorado),Tribes assert water rights on Colorado River B...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Tribal Nations, State Government, Federal Gove...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,3,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
1,2,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Native American tribes assert water rights on ...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Southern Ute Indian Tribe, Ute Mountain Tribe,...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,2,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
4,5,USGS1-50.docx,The Aspen Times (Colorado),Historically excluded from Colorado River poli...,False,19-Dec-21,2021.0,NaN,NaN,11.0,2021.0,Y,Y,Upper San Juan,140801,14,Southern Ute Indian Reservation,NaN,NaN,NaN,NaN,Rural,Intergovernmental issues,State and federal officials say that Tribal Na...,"Sothern Ute Indian Tribe, Ute Mountain Tribe, ...",-1.0,Interaction between tribal nations and state/f...,Lack of tribal representation,0,0,2,6,0,0,0,7,0,0,18,0,0,0,0,0,0,0,0,0
5,6,USGS1-50.docx,The Arizona Republic (Phoenix),Everyone loses if we cannot agree on how we us...,False,22-Apr-17,2017.0,NaN,NaN,4.0,2017.0,Y,Y,Entire Lower Colorado Basin,NaN,15,State of Arizona,NaN,NaN,AZ,4,Both,Intergovernmental issues,Water management agencies are in a legal dispu...,"Water Managers, All Water Users, Conservation ...",2.0,Event is delays in negotiations between state/...,NaN,0,0,10,11,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
7,8,USGS1-50.docx,"Navajo Times (Window Rock, Arizona)","Colorado River, stolen by law; Indigenous nati...",False,17-Mar-22,2022.0,NaN,NaN,3.0,2022.0,Y,Y,Entire Colorado River Basin,NaN,"14, 15",Entire Colorado River Basin,NaN,NaN,NaN,NaN,Both,Intergovernmental issues,"Amidst ongoing drought, the Colorado River Ind...","Colorado River Indian Tribes, State Government...",2.0,Although the article focuses quite a bit on hi...,NaN,0,0,0,4,0,0,0,6,0,0,15,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,258,USGS301-350.docx,The Arizona Republic (Phoenix),"At Canyon, water battle rages anew",False,22-Feb-09,2009.0,1,NaN,1.0,2009.0,Y,Y,Upper Colorado-Dirty Devil,140700,14,"Glen Canyon Dam, AZ",NaN,NaN,AZ,4,Both,Instream water rights,"After formal protests were ignored, the Superi...","Federal Government, State Government, Environm...",-3.0,Event is submission of formal complaint memo f...,Shallow engagement strategies,0,0,5,0,10,0,0,0,0,0,2,0,0,0,4,0,0,0,0,0
258,259,USGS301-350.docx,The Salt Lake Tribune,Alder: A new set of negotiations need for The ...,False,29-Aug-08,2008.0,8,NaN,8.0,2008.0,Y,Y,Entire Colorado River Basin,NaN,"14, 15",Utah,NaN,NaN,UT,49,Both,Intergovernmental issues,An op ed written by the Associate Dean for Aca...,"State Government, Federal Government, Environm...",-1.0,Event is letter written by dean disputing comm...,NaN,0,0,0,1,0,0,0,0,0,0,4,0,0,0,2,0,0,0,2,0
260,261,USGS301-350.docx,Farmington Daily Times (New Mexico),Experts predict low San Juan County river flow...,False,11-Apr-15,2015.0,4,NaN,4.0,2015.0,Y,Y,Lower San Juan,140802,14,San Juan River,NaN,NaN,NaN,NaN,Both,Drought,The Colorado Basin River Forecast Center predi...,"Navajo Nation, State Government, Water Manager...",-1.0,Event is release of forecast which prompts wat...,Devaluing tribal land and resources,0,0,1,4,0,0,0,0,0,0,7,0,0,0,0,0,0,0,0,0
262,263,USGS301-350.docx,Associated Press State & Local,Officials: Arizona will miss US deadline for k...,False,20-Feb-19,2019.0,2/19/2019,19.0,2.0,2019.0,Y,Y,Entire Lower Colorado Basin,NaN,15,State of Arizona,NaN,NaN,AZ,4,Both,Conservation; Water rights more generally,The state of Arizona announced they won't have...,"State Government, Federal Government, All Wate...",-2.0,Scored a -2 based on the disagreements among t...,Inequitable government access/relationship,0,0,0,6,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0
265,266,USGS301-350.docx,Casa Grande Dispatch (AZ),California water district lawsuit threatens dr...,False,18-Apr-19,2019.0,4,NaN,4.0,2019.0,Y,Y,Entire Colorado River Basin,NaN,"14, 15","State of Arizona, State of California",NaN,NaN,AZ; CA,04; 06,Both,Intergovernmental issues,The event is that California's Imperial Irriga...,"All Water Users, Agriculture, State Government...",-4.0,Scored based on the fact that the event is act...,NaN,1,0,3,9,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0

In [65]:
df_conflict['State'] = df_conflict['State'].str.split('; ', expand=True).stack().value_count()

AttributeError: 'Series' object has no attribute 'value_count'